name: liconic_module
services:
  liconic_module:
    container_name: liconic_module
    image: ${IMAGE}
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - ${IMAGE}:latest
        - ${IMAGE}:${PROJECT_VERSION}
        - ${IMAGE}:dev
    command: python -m liconic_rest_node --port 2010 --device ${DEVICE} --resources_path ${RESOURCES_PATH}
    privileged: true
    env_file: .env
    volumes:
      - ./src:/home/app/liconic_module/src
      - ./tests:/home/app/liconic_module/tests
      - ~/liconic_temp:/root/liconic_temp
    ports:
      - 2010:2010
